Update aqua-ci.yml

diff --git a/.github/workflows/aqua-ci.yml b/.github/workflows/aqua-ci.yml
--- a/.github/workflows/aqua-ci.yml
+++ b/.github/workflows/aqua-ci.yml
@@ -97,7 +97,7 @@ jobs:
           
       - name: Image Scan with Aqua SaaS Scanner
         run: | 
-          docker run -e env=uat \
+          docker run  \ 
             --rm \
             -v /var/run/docker.sock:/var/run/docker.sock \
             -v $(pwd):/scan-output \
@@ -107,7 +107,8 @@ jobs:
             --local ${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
             --sariffile /scan-output/image-results.sarif \
             --htmlfile /scan-output/image-results.html \
-            --layer-vulnerabilities 
+            --layer-vulnerabilities
+            #--layer-vulnerabilities 
             # --scan-malware \
             # --collect-sensitive \
             # --show-negligible \
@@ -129,23 +130,26 @@ jobs:
           path: image-results.html
 
 
-      - name: SBOM/Manifest Generation
+      - name: Manifest Generation
         run: |
-          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
-          curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
+          export BILLY_SERVER=https://billy.asia-1.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
           curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-
           if ! cat install.sh.checksum | sha256sum --check; then
-            echo "install.sh checksum failed"
-            exit 1
+          echo "install.sh checksum failed"
+          exit 1
           fi
-
           BINDIR="." sh install.sh
           rm install.sh install.sh.checksum
-
           ./billy generate \
             --access-token "${{ secrets.GITHUB_TOKEN }}" \
             --aqua-key "${{ secrets.AQUA_KEY }}" \
             --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-            --cspm-url https://eu-1.api.cloudsploit.com \
-            --artifact-path "${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}"
+            --cspm-url https://asia-1.api.cloudsploit.com \
+            --artifact-path "${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}" 
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
+            # --artifact-path "${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}"
